/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface WaApiConfigDTO { 
    waapiConfId?: number;
    instanceId?: string;
    instanceStatus?: string;
    displayName?: string;
    formattedNumber?: string;
    profilePicUrl?: string;
    lastQrCode?: string;
    owner?: string;
    explanation?: string;
    message?: string;
    creationDate?: Date;
    updateDate?: Date;
}