/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BranchConfiguration } from './branchConfiguration';
import { BranchSchedule } from './branchSchedule';

export interface BranchResponseEntity { 
    name?: string;
    address?: string;
    email?: string;
    phone?: string;
    vat?: string;
    type?: BranchResponseEntity.TypeEnum;
    branchCode?: string;
    role?: BranchResponseEntity.RoleEnum;
    branchConfiguration?: BranchConfiguration;
    branchSchedule?: BranchSchedule;
}
export namespace BranchResponseEntity {
    export type TypeEnum = 'RESTAURANT' | 'SUPPLIER';
    export const TypeEnum = {
        RESTAURANT: 'RESTAURANT' as TypeEnum,
        SUPPLIER: 'SUPPLIER' as TypeEnum
    };
    export type RoleEnum = 'PROPRIETARIO' | 'AMMINISTRATORE' | 'RESPONSABILE' | 'DIPENDENTE' | 'BARMAN' | 'CAMERIERE' | 'SMM';
    export const RoleEnum = {
        PROPRIETARIO: 'PROPRIETARIO' as RoleEnum,
        AMMINISTRATORE: 'AMMINISTRATORE' as RoleEnum,
        RESPONSABILE: 'RESPONSABILE' as RoleEnum,
        DIPENDENTE: 'DIPENDENTE' as RoleEnum,
        BARMAN: 'BARMAN' as RoleEnum,
        CAMERIERE: 'CAMERIERE' as RoleEnum,
        SMM: 'SMM' as RoleEnum
    };
}