/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Branch } from './branch';
import { DailyOpeningTime } from './dailyOpeningTime';
import { LocalTime } from './localTime';

export interface BranchSchedule { 
    id?: number;
    branch?: Branch;
    dailyOpeningTimes?: { [key: string]: DailyOpeningTime; };
    openingTime?: LocalTime;
    closingTime?: LocalTime;
    maxPeopleAllowed?: number;
}