/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BranchConfiguration } from './branchConfiguration';
import { BranchSchedule } from './branchSchedule';

export interface Branch { 
    branchId?: number;
    branchCode?: string;
    name?: string;
    email?: string;
    address?: string;
    phoneNumber?: string;
    vat?: string;
    type?: Branch.TypeEnum;
    branchSchedule?: BranchSchedule;
    branchConfiguration?: BranchConfiguration;
}
export namespace Branch {
    export type TypeEnum = 'RESTAURANT' | 'SUPPLIER';
    export const TypeEnum = {
        RESTAURANT: 'RESTAURANT' as TypeEnum,
        SUPPLIER: 'SUPPLIER' as TypeEnum
    };
}